#!/usr/bin/env python3
"""
マクロパネル組み立てスクリプト (Block B / Block C-macro)
------------------------------------------------------------
data/macro/ に置いた World Bank (WDI) / IHME / WHO の CSV から、
分析用のパネル `panel_merged.csv` / `panel_with_inactivity.csv` を生成する。

入力 (data/macro/):
  - worldbank_wdi.csv           : download_macro.py で生成
  - ihme_depression.csv         : 手動ダウンロード
  - ihme_suicide.csv            : 手動ダウンロード
  - ihme_homicide.csv           : 手動ダウンロード
  - who_ncd_pac.csv             : 手動ダウンロード (身体不活発率など)

出力 (data/macro/):
  - panel_merged.csv
  - panel_with_inactivity.csv   : WHOデータが結合できた場合のみ

注意:
  - IHME/WHO はファイル形式や列名が揺れやすいので、列の自動推定に失敗したら
    エラーメッセージに出る列名を見て手元でCSVを整形してください。
  - 国名マッチは "Country" (WDI) と IHME/WHO の location/country 名を
    ざっくり正規化して突合します。完全一致しない国が出た場合は警告します。
"""

from __future__ import annotations

import argparse
import os
import re
import sys

import pandas as pd


def canonical_country(name: str) -> str:
    if name is None:
        return ""
    s = str(name).strip().lower()
    s = s.replace("&", "and")
    s = re.sub(r"[\.,'\(\)\[\]/-]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    if s.startswith("the "):
        s = s[4:]
    return s


def pick_col(df: pd.DataFrame, candidates: list[str]) -> str | None:
    col_map = {c.lower(): c for c in df.columns}
    for c in candidates:
        key = c.lower()
        if key in col_map:
            return col_map[key]
    return None


def read_delimited(path: str) -> pd.DataFrame:
    for sep in [",", "\t", "|"]:
        try:
            df = pd.read_csv(path, sep=sep, low_memory=False)
            if df.shape[1] > 2:
                return df
        except Exception:
            continue
    return pd.read_csv(path, low_memory=False)


def load_wdi(worldbank_path: str) -> pd.DataFrame:
    df = pd.read_csv(worldbank_path)
    if "indicator" not in df.columns:
        raise ValueError("worldbank_wdi.csv must include 'indicator' column (generated by download_macro.py).")

    code_col = pick_col(df, ["economy", "code", "iso3"])
    country_col = pick_col(df, ["country"])
    if code_col is None:
        raise ValueError("Cannot find ISO3 code column (expected 'economy') in worldbank_wdi.csv.")
    if country_col is None:
        country_col = code_col

    year_cols = [c for c in df.columns if re.match(r"^(YR)?\d{4}$", str(c))]
    if not year_cols:
        raise ValueError("No year columns found in worldbank_wdi.csv (expected YR1990..).")

    long = df.melt(
        id_vars=[code_col, country_col, "indicator"],
        value_vars=year_cols,
        var_name="year",
        value_name="value",
    )
    long["year"] = long["year"].astype(str).str.extract(r"(\d{4})")[0]
    long = long.dropna(subset=["year"])
    long["year"] = long["year"].astype(int)
    long["value"] = pd.to_numeric(long["value"], errors="coerce")

    wide = (
        long.pivot_table(
            index=[code_col, country_col, "year"],
            columns="indicator",
            values="value",
            aggfunc="first",
        )
        .reset_index()
    )

    # Flatten columns
    wide.columns = [str(c) for c in wide.columns]

    # Rename core indicators
    rename = {
        code_col: "code",
        country_col: "country",
        "IT.NET.USER.ZS": "internet",
        # GDP per capita: prefer PPP (paper uses 2017 PPP) if present.
        "NY.GDP.PCAP.PP.KD": "gdp_ppp_2017",
        "NY.GDP.PCAP.CD": "gdp_current_usd",
        "SP.POP.TOTL": "population",
        "SL.SRV.EMPL.ZS": "service_employment",
        # Education variants
        "SE.SCH.LIFE": "education_years",
        "SE.ADJ.ENRR.PB": "education_enrollment_adjusted",
    }
    wide = wide.rename(columns={k: v for k, v in rename.items() if k in wide.columns})

    # Choose GDP series (prefer PPP if present)
    if "gdp_ppp_2017" in wide.columns and wide["gdp_ppp_2017"].notna().any():
        wide["gdp"] = wide["gdp_ppp_2017"]
    elif "gdp_current_usd" in wide.columns:
        wide["gdp"] = wide["gdp_current_usd"]

    # Choose education series for ratio (prefer years if present)
    if "education_years" in wide.columns:
        wide["education"] = wide["education_years"]
    elif "education_enrollment_adjusted" in wide.columns:
        wide["education"] = wide["education_enrollment_adjusted"]

    wide["country_key"] = wide["country"].map(canonical_country)
    return wide


def load_ihme(
    path: str,
    value_name: str,
    *,
    expected_cause: str | None = None,
    expected_measure: str | None = None,
    expected_metric: str | None = None,
    expected_sex: str | None = "Both",
    expected_age: str | None = "Age-standardized",
) -> pd.DataFrame:
    df = read_delimited(path)

    # If the user exported "too much" from the IHME UI (multiple ages/sexes/metrics/measures/causes),
    # try to subset to the intended slice when metadata columns are available.
    measure_col = pick_col(df, ["measure_name", "measure", "measure name"])
    metric_col = pick_col(df, ["metric_name", "metric", "metric name"])
    sex_col = pick_col(df, ["sex_name", "sex", "sex name"])
    age_col = pick_col(df, ["age_name", "age", "age name"])
    cause_col = pick_col(df, ["cause_name", "cause", "cause name"])

    def _norm_series(col: str) -> pd.Series:
        return df[col].astype(str).str.strip().str.lower()

    def _debug_unique(col: str, limit: int = 8) -> str:
        vals = _norm_series(col).dropna().unique().tolist()
        vals = [v for v in vals if v]
        vals = sorted(vals)[:limit]
        return ", ".join(vals) if vals else "(none)"

    def _filter_eq(col: str, expected: str) -> None:
        nonlocal df
        if col is None:
            return
        exp = str(expected).strip().lower()
        df = df[_norm_series(col) == exp]

    def _filter_contains(col: str, expected: str) -> None:
        nonlocal df
        if col is None:
            return
        exp = str(expected).strip().lower()
        df = df[_norm_series(col).str.contains(exp, na=False)]

    def _filter_sex(col: str, expected: str) -> None:
        nonlocal df
        if col is None:
            return
        exp = str(expected).strip().lower()
        s = _norm_series(col)
        if exp == "both":
            df = df[s.str.startswith("both", na=False)]
        else:
            df = df[s == exp]

    def _filter_age(col: str, expected: str) -> None:
        nonlocal df
        if col is None:
            return
        exp = str(expected).strip().lower()
        s = _norm_series(col)
        if "standard" in exp:
            df = df[s.str.contains("standard", na=False)]
        else:
            df = df[s == exp]

    if expected_measure is not None:
        _filter_eq(measure_col, expected_measure)
    if expected_metric is not None:
        _filter_eq(metric_col, expected_metric)
    if expected_sex is not None:
        _filter_sex(sex_col, expected_sex)
    if expected_age is not None:
        _filter_age(age_col, expected_age)
    if expected_cause is not None:
        # cause labels sometimes include commas/extra qualifiers; use contains.
        _filter_contains(cause_col, expected_cause)

    if df.empty:
        parts = []
        if measure_col is not None:
            parts.append(f"{measure_col}=[{_debug_unique(measure_col)}]")
        if metric_col is not None:
            parts.append(f"{metric_col}=[{_debug_unique(metric_col)}]")
        if sex_col is not None:
            parts.append(f"{sex_col}=[{_debug_unique(sex_col)}]")
        if age_col is not None:
            parts.append(f"{age_col}=[{_debug_unique(age_col)}]")
        if cause_col is not None:
            parts.append(f"{cause_col}=[{_debug_unique(cause_col)}]")
        hint = "; ".join(parts) if parts else "No metadata columns detected."
        raise ValueError(
            f"IHME CSV is empty after filtering for the intended slice ({os.path.basename(path)}). "
            f"Please re-export from IHME with: measure={expected_measure}, metric={expected_metric}, "
            f"sex={expected_sex}, age={expected_age}, cause={expected_cause}. "
            f"Found values: {hint}"
        )

    country_col = pick_col(df, ["location", "location_name", "country", "country_name"])
    year_col = pick_col(df, ["year", "year_id", "date"])
    value_col = pick_col(df, ["val", "value", "mean", "rate"])

    missing = [k for k, v in [("country", country_col), ("year", year_col), ("value", value_col)] if v is None]
    if missing:
        raise ValueError(
            f"IHME CSV parse failed for {os.path.basename(path)}. Missing columns: {', '.join(missing)}. "
            f"Available columns: {list(df.columns)}"
        )

    out = df[[country_col, year_col, value_col]].copy()
    out = out.rename(columns={country_col: "country_raw", year_col: "year", value_col: value_name})
    out["year"] = pd.to_numeric(out["year"], errors="coerce")
    out = out.dropna(subset=["year"])
    out["year"] = out["year"].astype(int)
    out[value_name] = pd.to_numeric(out[value_name], errors="coerce")

    out["country_key"] = out["country_raw"].map(canonical_country)
    out = out.dropna(subset=["country_key"])
    out = out.groupby(["country_key", "year"], as_index=False)[value_name].mean()
    return out


def load_owid_grapher(path: str, value_name: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    code_col = pick_col(df, ["code", "Code"])
    year_col = pick_col(df, ["year", "Year"])
    if code_col is None or year_col is None:
        raise ValueError(f"OWID grapher CSV must include Code/Year columns: {os.path.basename(path)}")

    # Prefer the first non-metadata column as the value
    meta = {"entity", "code", "year", "world region according to owid"}
    value_candidates = [c for c in df.columns if c.strip().lower() not in meta]
    if not value_candidates:
        raise ValueError(f"Cannot identify value column in OWID CSV: {os.path.basename(path)}")
    value_col = value_candidates[0]

    out = df[[code_col, year_col, value_col]].copy()
    out = out.rename(columns={code_col: "code", year_col: "year", value_col: value_name})
    out["code"] = out["code"].astype(str)
    out["year"] = pd.to_numeric(out["year"], errors="coerce")
    out = out.dropna(subset=["year"])
    out["year"] = out["year"].astype(int)
    out[value_name] = pd.to_numeric(out[value_name], errors="coerce")
    out = out[out["code"].str.len() == 3].copy()
    out = out.groupby(["code", "year"], as_index=False)[value_name].mean()
    return out


def load_code_year_value(path: str, value_name: str) -> tuple[pd.DataFrame, list[str]]:
    df = read_delimited(path)
    code_col = pick_col(df, ["code", "iso3", "spatialdim", "spatial_dim"])
    year_col = pick_col(df, ["year", "time", "timedim"])
    value_col = value_name if value_name in df.columns else pick_col(df, ["value", "val", "numericvalue", value_name])

    if code_col is None:
        raise ValueError(f"Cannot find code column in {os.path.basename(path)}. Columns: {list(df.columns)}")
    if value_col is None:
        raise ValueError(f"Cannot find value column in {os.path.basename(path)}. Columns: {list(df.columns)}")

    keep_cols = [code_col, value_col]
    if year_col is not None:
        keep_cols.append(year_col)

    out = df[keep_cols].copy()
    out = out.rename(columns={code_col: "code", value_col: value_name})
    out["code"] = out["code"].astype(str)
    out[value_name] = pd.to_numeric(out[value_name], errors="coerce")

    keys: list[str]
    if year_col is not None:
        out = out.rename(columns={year_col: "year"})
        out["year"] = pd.to_numeric(out["year"], errors="coerce")
        out = out.dropna(subset=["year"])
        out["year"] = out["year"].astype(int)
        out = out[out["code"].str.len() == 3].copy()
        out = out.groupby(["code", "year"], as_index=False)[value_name].mean()
        keys = ["code", "year"]
    else:
        out = out[out["code"].str.len() == 3].copy()
        out = out.groupby(["code"], as_index=False)[value_name].mean()
        keys = ["code"]

    return out, keys


def load_who(path: str) -> tuple[pd.DataFrame, list[str]]:
    df = read_delimited(path)
    code_col = pick_col(df, ["code", "iso3", "spatialdim", "spatial_dim"])
    year_col = pick_col(df, ["year", "time", "date", "timedim"])
    value_col = pick_col(df, ["physical_inactivity", "value", "val", "numericvalue", "rate", "pct", "percent"])

    if code_col is not None and value_col is not None:
        out = df[[code_col] + ([year_col] if year_col else []) + [value_col]].copy()
        out = out.rename(columns={code_col: "code", value_col: "physical_inactivity"})
        out["code"] = out["code"].astype(str)
        out["physical_inactivity"] = pd.to_numeric(out["physical_inactivity"], errors="coerce")
        if year_col:
            out = out.rename(columns={year_col: "year"})
            out["year"] = pd.to_numeric(out["year"], errors="coerce")
            out = out.dropna(subset=["year"])
            out["year"] = out["year"].astype(int)
            out = out[out["code"].str.len() == 3].copy()
            out = out.groupby(["code", "year"], as_index=False)["physical_inactivity"].mean()
            return out, ["code", "year"]
        out = out[out["code"].str.len() == 3].copy()
        out = out.groupby(["code"], as_index=False)["physical_inactivity"].mean()
        return out, ["code"]

    # Fallback: country-name merge
    country_col = pick_col(df, ["country", "location", "location_name", "country_name"])
    if country_col is None or value_col is None:
        raise ValueError(
            f"WHO CSV parse failed for {os.path.basename(path)}. "
            f"Available columns: {list(df.columns)}"
        )

    out = df[[country_col] + ([year_col] if year_col else []) + [value_col]].copy()
    out = out.rename(columns={country_col: "country_raw", value_col: "physical_inactivity"})
    out["country_key"] = out["country_raw"].map(canonical_country)
    out["physical_inactivity"] = pd.to_numeric(out["physical_inactivity"], errors="coerce")
    if year_col:
        out = out.rename(columns={year_col: "year"})
        out["year"] = pd.to_numeric(out["year"], errors="coerce")
        out = out.dropna(subset=["year"])
        out["year"] = out["year"].astype(int)
        out = out.groupby(["country_key", "year"], as_index=False)["physical_inactivity"].mean()
        return out, ["country_key", "year"]

    out = out.groupby(["country_key"], as_index=False)["physical_inactivity"].mean()
    return out, ["country_key"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--macro-dir", default=os.path.join(os.path.dirname(__file__), "macro"))
    parser.add_argument("--worldbank", default="worldbank_wdi.csv")
    parser.add_argument("--ihme-depression", default="ihme_depression.csv")
    parser.add_argument("--ihme-suicide", default="ihme_suicide.csv")
    parser.add_argument("--ihme-homicide", default="ihme_homicide.csv")
    parser.add_argument("--who-inactivity", default="who_ncd_pac.csv")
    parser.add_argument("--who-suicide", default="who_suicide_mh12.csv")
    parser.add_argument("--owid-education", default="owid_mean_years_of_schooling.csv")
    parser.add_argument("--owid-homicide", default="owid_homicide_rate_unodc.csv")
    args = parser.parse_args()

    macro_dir = os.path.abspath(args.macro_dir)
    os.makedirs(macro_dir, exist_ok=True)

    worldbank_path = os.path.join(macro_dir, args.worldbank)
    if not os.path.exists(worldbank_path):
        print(f"ERROR: {worldbank_path} not found.")
        print("Run: python data/download_macro.py  (requires wbgapi) ")
        return 1

    wdi = load_wdi(worldbank_path)
    print(f"WDI panel: rows={len(wdi):,}, countries={wdi['code'].nunique():,}, years={wdi['year'].nunique():,}")

    # Optional OWID education (prefer for ratio denominator if available)
    panel = wdi.copy()
    owid_edu_path = os.path.join(macro_dir, args.owid_education)
    if os.path.exists(owid_edu_path):
        try:
            edu = load_owid_grapher(owid_edu_path, "education_owid")
            panel = panel.merge(edu, on=["code", "year"], how="left")
            if "education_owid" in panel.columns and panel["education_owid"].notna().any():
                if "education" in panel.columns:
                    panel["education"] = panel["education_owid"].combine_first(panel["education"])
                else:
                    panel["education"] = panel["education_owid"]
            print(f"Merged OWID education: {os.path.basename(owid_edu_path)}")
        except Exception as e:
            print(f"[WARN] OWID education parse failed: {e}")

    # Merge IHME outcomes (optional but recommended for depression)
    for fname, col in [
        (args.ihme_depression, "depression_prevalence"),
        (args.ihme_suicide, "suicide_ihme"),
        (args.ihme_homicide, "homicide_ihme"),
    ]:
        path = os.path.join(macro_dir, fname)
        if not os.path.exists(path):
            print(f"[WARN] Missing: {path} (skipped)")
            continue
        try:
            spec = {}
            if fname == args.ihme_depression:
                spec = {"expected_cause": "Depressive disorders", "expected_measure": "Prevalence", "expected_metric": "Rate"}
            elif fname == args.ihme_suicide:
                spec = {"expected_cause": "Self-harm", "expected_measure": "Deaths", "expected_metric": "Rate"}
            elif fname == args.ihme_homicide:
                spec = {"expected_cause": "Interpersonal violence", "expected_measure": "Deaths", "expected_metric": "Rate"}
            ihme = load_ihme(path, col, **spec)
        except Exception as e:
            print(f"ERROR: {path} parse failed: {e}")
            return 1
        panel = panel.merge(ihme, on=["country_key", "year"], how="left")
        print(f"Merged {fname}: now columns include '{col}'")

    # Optional WHO suicide (hard outcome; use if present)
    who_suicide_path = os.path.join(macro_dir, args.who_suicide)
    if os.path.exists(who_suicide_path):
        try:
            who_sui, who_keys = load_code_year_value(who_suicide_path, "suicide")
            panel = panel.merge(who_sui.rename(columns={"suicide": "suicide_who"}), on=who_keys, how="left")
            if panel.get("suicide_who") is not None and panel["suicide_who"].notna().any():
                panel["suicide"] = panel["suicide_who"]
            elif "suicide_ihme" in panel.columns:
                panel["suicide"] = panel["suicide_ihme"]
            print(f"Merged WHO suicide: {os.path.basename(who_suicide_path)}")
        except Exception as e:
            print(f"[WARN] WHO suicide parse failed: {e}")
    elif "suicide_ihme" in panel.columns:
        panel["suicide"] = panel["suicide_ihme"]

    # Optional OWID homicide (UNODC)
    owid_hom_path = os.path.join(macro_dir, args.owid_homicide)
    if os.path.exists(owid_hom_path):
        try:
            hom = load_owid_grapher(owid_hom_path, "homicide_unodc")
            panel = panel.merge(hom, on=["code", "year"], how="left")
            if panel.get("homicide_unodc") is not None and panel["homicide_unodc"].notna().any():
                panel["homicide"] = panel["homicide_unodc"]
            elif "homicide_ihme" in panel.columns:
                panel["homicide"] = panel["homicide_ihme"]
            print(f"Merged OWID homicide: {os.path.basename(owid_hom_path)}")
        except Exception as e:
            print(f"[WARN] OWID homicide parse failed: {e}")
    elif "homicide_ihme" in panel.columns:
        panel["homicide"] = panel["homicide_ihme"]

    # Interpolate education data within each country (OWID provides only 5-yearly data;
    # mean years of schooling changes slowly, so linear interpolation is defensible).
    if "education" in panel.columns and panel["education"].notna().any():
        edu_before = panel["education"].notna().sum()
        panel = panel.sort_values(["code", "year"])
        panel["education"] = panel.groupby("code")["education"].transform(
            lambda s: s.interpolate(method="linear", limit_direction="both")
        )
        edu_after = panel["education"].notna().sum()
        print(f"Education interpolated: {edu_before:,} → {edu_after:,} non-null values "
              f"(linear within-country)")

    # Derived variables
    if "education" in panel.columns and "internet" in panel.columns:
        internet = pd.to_numeric(panel["internet"], errors="coerce")
        education = pd.to_numeric(panel["education"], errors="coerce")
        internet_for_ratio = internet
        if education.max(skipna=True) <= 1.5 and internet.max(skipna=True) > 1.5:
            internet_for_ratio = internet / 100.0
        panel["intake_ratio"] = internet_for_ratio / education

    if "internet" in panel.columns and "gdp" in panel.columns:
        internet = pd.to_numeric(panel["internet"], errors="coerce")
        gdp = pd.to_numeric(panel["gdp"], errors="coerce")
        # Paper definition: proxy = Internet(%) × GDP/capita($) / 1000.
        # WDI IT.NET.USER.ZS is already in percent (0–100). If a panel is supplied
        # with internet in share (0–1), convert to percent for consistency.
        internet_pct = internet * 100.0 if internet.max(skipna=True) <= 1.5 else internet
        panel["ad_proxy"] = internet_pct * gdp / 1000.0

    # Save base panel
    out_panel = os.path.join(macro_dir, "panel_merged.csv")
    panel.to_csv(out_panel, index=False)
    print(f"Saved: {out_panel}")

    # WHO inactivity (optional)
    who_path = os.path.join(macro_dir, args.who_inactivity)
    if os.path.exists(who_path):
        try:
            who, merge_keys = load_who(who_path)
        except Exception as e:
            print(f"ERROR: {who_path} parse failed: {e}")
            return 1

        panel2 = panel.merge(who, on=merge_keys, how="left")

        if "physical_inactivity" in panel2.columns and panel2["physical_inactivity"].notna().any():
            out_inact = os.path.join(macro_dir, "panel_with_inactivity.csv")
            panel2.to_csv(out_inact, index=False)
            print(f"Saved: {out_inact}")
        else:
            print("[WARN] WHO inactivity merged, but no non-null values found. panel_with_inactivity.csv not written.")
    else:
        print(f"[WARN] Missing: {who_path} (skipped)")

    # Diagnostics: how many countries have IHME depression?
    if "depression_prevalence" in panel.columns:
        n_dep = panel.dropna(subset=["depression_prevalence"])["code"].nunique()
        print(f"Countries with depression data: {n_dep:,}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
